version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data 
  db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      networks:
      - node-red-net
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: 12345678

  app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      networks:
      - node-red-net
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
        

volumes:
  node-red-data:

networks:
  node-red-net: