version: '3.2'

services:

   node-red:
      image: nodered/node-red:latest
      environment:
        - TZ=Europe/Amsterdam
      ports:
        - "1880:1880"
      networks:
        - node-red-net
      volumes:
        - node-red-data:/data

   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '3306:3306'
      networks:
       - node-red-net
      environment:
        MYSQL_ROOT_PASSWORD: 12345678
      

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '80:80'
      networks:
       - node-red-net
      environment:
        PMA_HOST: db

volumes:
  node-red-data:

networks:
  node-red-net:
      driver: bridge
